[build]
  command = "bun run build"
  publish = ".next"

[plugins]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "1.3.4"

[functions]
  directory = "netlify/functions"

[build.edge_functions]
  directory = "netlify/edge-functions"
